Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Entity\\CartItem",
            "name": "CartItem",
            "summary": "Class\u0020CartItem",
            "url": "classes/App-Entity-CartItem.html"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Gets\u0020the\u0020ID\u0020of\u0020the\u0020cart\u0020item.",
            "url": "classes/App-Entity-CartItem.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003AgetCart\u0028\u0029",
            "name": "getCart",
            "summary": "Gets\u0020the\u0020cart\u0020associated\u0020with\u0020this\u0020item.",
            "url": "classes/App-Entity-CartItem.html#method_getCart"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003AsetCart\u0028\u0029",
            "name": "setCart",
            "summary": "Sets\u0020the\u0020cart\u0020associated\u0020with\u0020this\u0020item.",
            "url": "classes/App-Entity-CartItem.html#method_setCart"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003AgetQuantity\u0028\u0029",
            "name": "getQuantity",
            "summary": "Gets\u0020the\u0020quantity\u0020of\u0020this\u0020item\u0020in\u0020the\u0020cart.",
            "url": "classes/App-Entity-CartItem.html#method_getQuantity"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003AsetQuantity\u0028\u0029",
            "name": "setQuantity",
            "summary": "Sets\u0020the\u0020quantity\u0020of\u0020this\u0020item\u0020in\u0020the\u0020cart.",
            "url": "classes/App-Entity-CartItem.html#method_setQuantity"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003AgetLessons\u0028\u0029",
            "name": "getLessons",
            "summary": "Gets\u0020the\u0020lesson\u0020associated\u0020with\u0020this\u0020cart\u0020item.",
            "url": "classes/App-Entity-CartItem.html#method_getLessons"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003AsetLessons\u0028\u0029",
            "name": "setLessons",
            "summary": "Sets\u0020the\u0020lesson\u0020associated\u0020with\u0020this\u0020cart\u0020item.",
            "url": "classes/App-Entity-CartItem.html#method_setLessons"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003AgetCursus\u0028\u0029",
            "name": "getCursus",
            "summary": "Gets\u0020the\u0020cursus\u0020associated\u0020with\u0020this\u0020cart\u0020item.",
            "url": "classes/App-Entity-CartItem.html#method_getCursus"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003AsetCursus\u0028\u0029",
            "name": "setCursus",
            "summary": "Sets\u0020the\u0020cursus\u0020associated\u0020with\u0020this\u0020cart\u0020item.",
            "url": "classes/App-Entity-CartItem.html#method_setCursus"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-CartItem.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003A\u0024cart",
            "name": "cart",
            "summary": "",
            "url": "classes/App-Entity-CartItem.html#property_cart"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003A\u0024quantity",
            "name": "quantity",
            "summary": "",
            "url": "classes/App-Entity-CartItem.html#property_quantity"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003A\u0024lessons",
            "name": "lessons",
            "summary": "",
            "url": "classes/App-Entity-CartItem.html#property_lessons"
        },                {
            "fqsen": "\\App\\Entity\\CartItem\u003A\u003A\u0024cursus",
            "name": "cursus",
            "summary": "",
            "url": "classes/App-Entity-CartItem.html#property_cursus"
        },                {
            "fqsen": "\\App\\Entity\\Certificate",
            "name": "Certificate",
            "summary": "Class\u0020Certificate",
            "url": "classes/App-Entity-Certificate.html"
        },                {
            "fqsen": "\\App\\Entity\\Certificate\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Gets\u0020the\u0020ID\u0020of\u0020the\u0020certificate.",
            "url": "classes/App-Entity-Certificate.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Certificate\u003A\u003AgetCursus\u0028\u0029",
            "name": "getCursus",
            "summary": "Gets\u0020the\u0020cursus\u0020associated\u0020with\u0020this\u0020certificate.",
            "url": "classes/App-Entity-Certificate.html#method_getCursus"
        },                {
            "fqsen": "\\App\\Entity\\Certificate\u003A\u003AsetCursus\u0028\u0029",
            "name": "setCursus",
            "summary": "Sets\u0020the\u0020cursus\u0020associated\u0020with\u0020this\u0020certificate.",
            "url": "classes/App-Entity-Certificate.html#method_setCursus"
        },                {
            "fqsen": "\\App\\Entity\\Certificate\u003A\u003AgetLesson\u0028\u0029",
            "name": "getLesson",
            "summary": "Gets\u0020the\u0020lesson\u0020associated\u0020with\u0020this\u0020certificate.",
            "url": "classes/App-Entity-Certificate.html#method_getLesson"
        },                {
            "fqsen": "\\App\\Entity\\Certificate\u003A\u003AsetLesson\u0028\u0029",
            "name": "setLesson",
            "summary": "Sets\u0020the\u0020lesson\u0020associated\u0020with\u0020this\u0020certificate.",
            "url": "classes/App-Entity-Certificate.html#method_setLesson"
        },                {
            "fqsen": "\\App\\Entity\\Certificate\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "Gets\u0020the\u0020user\u0020who\u0020earned\u0020this\u0020certificate.",
            "url": "classes/App-Entity-Certificate.html#method_getUser"
        },                {
            "fqsen": "\\App\\Entity\\Certificate\u003A\u003AsetUser\u0028\u0029",
            "name": "setUser",
            "summary": "Sets\u0020the\u0020user\u0020who\u0020earned\u0020this\u0020certificate.",
            "url": "classes/App-Entity-Certificate.html#method_setUser"
        },                {
            "fqsen": "\\App\\Entity\\Certificate\u003A\u003A\u0024isCertified",
            "name": "isCertified",
            "summary": "",
            "url": "classes/App-Entity-Certificate.html#property_isCertified"
        },                {
            "fqsen": "\\App\\Entity\\Certificate\u003A\u003AsetCertified\u0028\u0029",
            "name": "setCertified",
            "summary": "Sets\u0020the\u0020certified\u0020status\u0020of\u0020the\u0020certificate.",
            "url": "classes/App-Entity-Certificate.html#method_setCertified"
        },                {
            "fqsen": "\\App\\Entity\\Certificate\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Certificate.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Certificate\u003A\u003A\u0024cursus",
            "name": "cursus",
            "summary": "",
            "url": "classes/App-Entity-Certificate.html#property_cursus"
        },                {
            "fqsen": "\\App\\Entity\\Certificate\u003A\u003A\u0024lesson",
            "name": "lesson",
            "summary": "",
            "url": "classes/App-Entity-Certificate.html#property_lesson"
        },                {
            "fqsen": "\\App\\Entity\\Certificate\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/App-Entity-Certificate.html#property_user"
        },                {
            "fqsen": "\\App\\Entity\\Course",
            "name": "Course",
            "summary": "Class\u0020Course",
            "url": "classes/App-Entity-Course.html"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Course.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Gets\u0020the\u0020ID\u0020of\u0020the\u0020course.",
            "url": "classes/App-Entity-Course.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Gets\u0020the\u0020title\u0020of\u0020the\u0020course.",
            "url": "classes/App-Entity-Course.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "Sets\u0020the\u0020title\u0020of\u0020the\u0020course.",
            "url": "classes/App-Entity-Course.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "Gets\u0020the\u0020content\u0020of\u0020the\u0020course.",
            "url": "classes/App-Entity-Course.html#method_getContent"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003AsetContent\u0028\u0029",
            "name": "setContent",
            "summary": "Sets\u0020the\u0020content\u0020of\u0020the\u0020course.",
            "url": "classes/App-Entity-Course.html#method_setContent"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003AgetLesson\u0028\u0029",
            "name": "getLesson",
            "summary": "Gets\u0020the\u0020lesson\u0020associated\u0020with\u0020this\u0020course.",
            "url": "classes/App-Entity-Course.html#method_getLesson"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003AsetLesson\u0028\u0029",
            "name": "setLesson",
            "summary": "Sets\u0020the\u0020lesson\u0020associated\u0020with\u0020this\u0020course.",
            "url": "classes/App-Entity-Course.html#method_setLesson"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003AgetAccessCourse\u0028\u0029",
            "name": "getAccessCourse",
            "summary": "",
            "url": "classes/App-Entity-Course.html#method_getAccessCourse"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003AaddAccessCourse\u0028\u0029",
            "name": "addAccessCourse",
            "summary": "Adds\u0020an\u0020access\u0020record\u0020to\u0020this\u0020course.",
            "url": "classes/App-Entity-Course.html#method_addAccessCourse"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003AremoveAccessCourse\u0028\u0029",
            "name": "removeAccessCourse",
            "summary": "Removes\u0020an\u0020access\u0020record\u0020from\u0020this\u0020course.",
            "url": "classes/App-Entity-Course.html#method_removeAccessCourse"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Returns\u0020the\u0020string\u0020representation\u0020of\u0020the\u0020course.",
            "url": "classes/App-Entity-Course.html#method___toString"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Course.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Entity-Course.html#property_title"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/App-Entity-Course.html#property_content"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003A\u0024lesson",
            "name": "lesson",
            "summary": "",
            "url": "classes/App-Entity-Course.html#property_lesson"
        },                {
            "fqsen": "\\App\\Entity\\Course\u003A\u003A\u0024accessCourse",
            "name": "accessCourse",
            "summary": "",
            "url": "classes/App-Entity-Course.html#property_accessCourse"
        },                {
            "fqsen": "\\App\\Entity\\Cursus",
            "name": "Cursus",
            "summary": "Class\u0020Cursus",
            "url": "classes/App-Entity-Cursus.html"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Cursus.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Gets\u0020the\u0020ID\u0020of\u0020the\u0020cursus.",
            "url": "classes/App-Entity-Cursus.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Gets\u0020the\u0020name\u0020of\u0020the\u0020cursus.",
            "url": "classes/App-Entity-Cursus.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Sets\u0020the\u0020name\u0020of\u0020the\u0020cursus.",
            "url": "classes/App-Entity-Cursus.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AgetPrice\u0028\u0029",
            "name": "getPrice",
            "summary": "Gets\u0020the\u0020price\u0020of\u0020the\u0020cursus.",
            "url": "classes/App-Entity-Cursus.html#method_getPrice"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AsetPrice\u0028\u0029",
            "name": "setPrice",
            "summary": "Sets\u0020the\u0020price\u0020of\u0020the\u0020cursus.",
            "url": "classes/App-Entity-Cursus.html#method_setPrice"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AgetTheme\u0028\u0029",
            "name": "getTheme",
            "summary": "Gets\u0020the\u0020theme\u0020associated\u0020with\u0020this\u0020cursus.",
            "url": "classes/App-Entity-Cursus.html#method_getTheme"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AsetTheme\u0028\u0029",
            "name": "setTheme",
            "summary": "Sets\u0020the\u0020theme\u0020associated\u0020with\u0020this\u0020cursus.",
            "url": "classes/App-Entity-Cursus.html#method_setTheme"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AgetLessons\u0028\u0029",
            "name": "getLessons",
            "summary": "",
            "url": "classes/App-Entity-Cursus.html#method_getLessons"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AaddLesson\u0028\u0029",
            "name": "addLesson",
            "summary": "Adds\u0020a\u0020lesson\u0020to\u0020this\u0020cursus.",
            "url": "classes/App-Entity-Cursus.html#method_addLesson"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AremoveLesson\u0028\u0029",
            "name": "removeLesson",
            "summary": "Removes\u0020a\u0020lesson\u0020from\u0020this\u0020cursus.",
            "url": "classes/App-Entity-Cursus.html#method_removeLesson"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Returns\u0020the\u0020string\u0020representation\u0020of\u0020the\u0020cursus.",
            "url": "classes/App-Entity-Cursus.html#method___toString"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AgetLessonsAsString\u0028\u0029",
            "name": "getLessonsAsString",
            "summary": "Gets\u0020the\u0020names\u0020of\u0020lessons\u0020in\u0020the\u0020cursus\u0020as\u0020a\u0020comma\u002Dseparated\u0020string.",
            "url": "classes/App-Entity-Cursus.html#method_getLessonsAsString"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AgetCertificates\u0028\u0029",
            "name": "getCertificates",
            "summary": "",
            "url": "classes/App-Entity-Cursus.html#method_getCertificates"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AaddCertificate\u0028\u0029",
            "name": "addCertificate",
            "summary": "Adds\u0020a\u0020certificate\u0020to\u0020this\u0020cursus.",
            "url": "classes/App-Entity-Cursus.html#method_addCertificate"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003AremoveCertificate\u0028\u0029",
            "name": "removeCertificate",
            "summary": "Removes\u0020a\u0020certificate\u0020from\u0020this\u0020cursus.",
            "url": "classes/App-Entity-Cursus.html#method_removeCertificate"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Cursus.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Entity-Cursus.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003A\u0024price",
            "name": "price",
            "summary": "",
            "url": "classes/App-Entity-Cursus.html#property_price"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003A\u0024theme",
            "name": "theme",
            "summary": "",
            "url": "classes/App-Entity-Cursus.html#property_theme"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003A\u0024lessons",
            "name": "lessons",
            "summary": "",
            "url": "classes/App-Entity-Cursus.html#property_lessons"
        },                {
            "fqsen": "\\App\\Entity\\Cursus\u003A\u003A\u0024certificates",
            "name": "certificates",
            "summary": "",
            "url": "classes/App-Entity-Cursus.html#property_certificates"
        },                {
            "fqsen": "\\App\\Entity\\ResetPasswordRequest",
            "name": "ResetPasswordRequest",
            "summary": "Class\u0020ResetPasswordRequest",
            "url": "classes/App-Entity-ResetPasswordRequest.html"
        },                {
            "fqsen": "\\App\\Entity\\ResetPasswordRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ResetPasswordRequest\u0020constructor.",
            "url": "classes/App-Entity-ResetPasswordRequest.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\ResetPasswordRequest\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Gets\u0020the\u0020ID\u0020of\u0020the\u0020reset\u0020password\u0020request.",
            "url": "classes/App-Entity-ResetPasswordRequest.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\ResetPasswordRequest\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "Gets\u0020the\u0020user\u0020associated\u0020with\u0020this\u0020reset\u0020password\u0020request.",
            "url": "classes/App-Entity-ResetPasswordRequest.html#method_getUser"
        },                {
            "fqsen": "\\App\\Entity\\ResetPasswordRequest\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-ResetPasswordRequest.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\ResetPasswordRequest\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/App-Entity-ResetPasswordRequest.html#property_user"
        },                {
            "fqsen": "\\App\\Entity\\Theme",
            "name": "Theme",
            "summary": "Class\u0020Theme",
            "url": "classes/App-Entity-Theme.html"
        },                {
            "fqsen": "\\App\\Entity\\Theme\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-Theme.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Theme\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Gets\u0020the\u0020ID\u0020of\u0020the\u0020theme.",
            "url": "classes/App-Entity-Theme.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Theme\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Gets\u0020the\u0020name\u0020of\u0020the\u0020theme.",
            "url": "classes/App-Entity-Theme.html#method_getName"
        },                {
            "fqsen": "\\App\\Entity\\Theme\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Sets\u0020the\u0020name\u0020of\u0020the\u0020theme.",
            "url": "classes/App-Entity-Theme.html#method_setName"
        },                {
            "fqsen": "\\App\\Entity\\Theme\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Converts\u0020the\u0020theme\u0020to\u0020a\u0020string\u0020representation.",
            "url": "classes/App-Entity-Theme.html#method___toString"
        },                {
            "fqsen": "\\App\\Entity\\Theme\u003A\u003AgetCursus\u0028\u0029",
            "name": "getCursus",
            "summary": "Gets\u0020the\u0020collection\u0020of\u0020cursus\u0020associated\u0020with\u0020this\u0020theme.",
            "url": "classes/App-Entity-Theme.html#method_getCursus"
        },                {
            "fqsen": "\\App\\Entity\\Theme\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Theme.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Theme\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Entity-Theme.html#property_name"
        },                {
            "fqsen": "\\App\\Entity\\Theme\u003A\u003A\u0024cursus",
            "name": "cursus",
            "summary": "",
            "url": "classes/App-Entity-Theme.html#property_cursus"
        },                {
            "fqsen": "\\App\\Entity\\User",
            "name": "User",
            "summary": "Class\u0020User",
            "url": "classes/App-Entity-User.html"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Entity-User.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Gets\u0020the\u0020ID\u0020of\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "Gets\u0020the\u0020email\u0020of\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_getEmail"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "Sets\u0020the\u0020email\u0020of\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_setEmail"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUserIdentifier\u0028\u0029",
            "name": "getUserIdentifier",
            "summary": "A\u0020visual\u0020identifier\u0020that\u0020represents\u0020this\u0020user.",
            "url": "classes/App-Entity-User.html#method_getUserIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetRoles\u0028\u0029",
            "name": "getRoles",
            "summary": "Gets\u0020the\u0020roles\u0020assigned\u0020to\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_getRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetRoles\u0028\u0029",
            "name": "setRoles",
            "summary": "Sets\u0020the\u0020roles\u0020for\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_setRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "Gets\u0020the\u0020hashed\u0020password\u0020of\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_getPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "Sets\u0020the\u0020password\u0020for\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_setPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AeraseCredentials\u0028\u0029",
            "name": "eraseCredentials",
            "summary": "Erases\u0020sensitive\u0020data\u0020from\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_eraseCredentials"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024isVerified",
            "name": "isVerified",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_isVerified"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetVerified\u0028\u0029",
            "name": "setVerified",
            "summary": "Sets\u0020the\u0020verification\u0020status\u0020of\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_setVerified"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetCourse\u0028\u0029",
            "name": "getCourse",
            "summary": "Gets\u0020the\u0020collection\u0020of\u0020access\u0020courses\u0020associated\u0020with\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_getCourse"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AaddCourse\u0028\u0029",
            "name": "addCourse",
            "summary": "Adds\u0020an\u0020access\u0020course\u0020to\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_addCourse"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AremoveCourse\u0028\u0029",
            "name": "removeCourse",
            "summary": "Removes\u0020an\u0020access\u0020course\u0020from\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_removeCourse"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Converts\u0020the\u0020user\u0020to\u0020a\u0020string\u0020representation.",
            "url": "classes/App-Entity-User.html#method___toString"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetCertificates\u0028\u0029",
            "name": "getCertificates",
            "summary": "Gets\u0020the\u0020collection\u0020of\u0020certificates\u0020associated\u0020with\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_getCertificates"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AaddCertificate\u0028\u0029",
            "name": "addCertificate",
            "summary": "Adds\u0020a\u0020certificate\u0020to\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_addCertificate"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AremoveCertificate\u0028\u0029",
            "name": "removeCertificate",
            "summary": "Removes\u0020a\u0020certificate\u0020from\u0020the\u0020user.",
            "url": "classes/App-Entity-User.html#method_removeCertificate"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_email"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024roles",
            "name": "roles",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_roles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_password"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024course",
            "name": "course",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_course"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024certificates",
            "name": "certificates",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_certificates"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        }            ]
);
