Search.appendIndex(
    [
                {
            "fqsen": "\\App\\DataFixtures\\CourseFixtures",
            "name": "CourseFixtures",
            "summary": "Fixture\u0020class\u0020responsible\u0020for\u0020loading\u0020sample\u0020Course\u0020data\u0020into\u0020the\u0020database.",
            "url": "classes/App-DataFixtures-CourseFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\CourseFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loads\u0020a\u0020set\u0020of\u0020predefined\u0020Course\u0020entities\u0020into\u0020the\u0020database.",
            "url": "classes/App-DataFixtures-CourseFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\CourseFixtures\u003A\u003AgetDependencies\u0028\u0029",
            "name": "getDependencies",
            "summary": "Returns\u0020an\u0020array\u0020of\u0020fixture\u0020dependencies.",
            "url": "classes/App-DataFixtures-CourseFixtures.html#method_getDependencies"
        },                {
            "fqsen": "\\App\\DataFixtures\\CursusFixtures",
            "name": "CursusFixtures",
            "summary": "Fixture\u0020class\u0020for\u0020loading\u0020sample\u0020Cursus\u0020entities\u0020into\u0020the\u0020database.",
            "url": "classes/App-DataFixtures-CursusFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\CursusFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loads\u0020a\u0020set\u0020of\u0020predefined\u0020Cursus\u0020entities\u0020into\u0020the\u0020database.",
            "url": "classes/App-DataFixtures-CursusFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\CursusFixtures\u003A\u003AgetDependencies\u0028\u0029",
            "name": "getDependencies",
            "summary": "Returns\u0020an\u0020array\u0020of\u0020fixture\u0020dependencies.",
            "url": "classes/App-DataFixtures-CursusFixtures.html#method_getDependencies"
        },                {
            "fqsen": "\\App\\DataFixtures\\CursusFixtures\u003A\u003ACURSUS_GUITARE_REFERENCE",
            "name": "CURSUS_GUITARE_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-CursusFixtures.html#constant_CURSUS_GUITARE_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\CursusFixtures\u003A\u003ACURSUS_PIANO_REFERENCE",
            "name": "CURSUS_PIANO_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-CursusFixtures.html#constant_CURSUS_PIANO_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\CursusFixtures\u003A\u003ACURSUS_DEVELOPPEMENT_REFERENCE",
            "name": "CURSUS_DEVELOPPEMENT_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-CursusFixtures.html#constant_CURSUS_DEVELOPPEMENT_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\CursusFixtures\u003A\u003ACURSUS_JARDINAGE_REFERENCE",
            "name": "CURSUS_JARDINAGE_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-CursusFixtures.html#constant_CURSUS_JARDINAGE_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\CursusFixtures\u003A\u003ACURSUS_CUISINE_REFERENCE",
            "name": "CURSUS_CUISINE_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-CursusFixtures.html#constant_CURSUS_CUISINE_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\CursusFixtures\u003A\u003ACURSUS_DRESSAGE_REFERENCE",
            "name": "CURSUS_DRESSAGE_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-CursusFixtures.html#constant_CURSUS_DRESSAGE_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures",
            "name": "LessonFixtures",
            "summary": "Fixture\u0020class\u0020for\u0020loading\u0020sample\u0020Lesson\u0020entities\u0020into\u0020the\u0020database.",
            "url": "classes/App-DataFixtures-LessonFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loads\u0020a\u0020set\u0020of\u0020predefined\u0020Lesson\u0020entities\u0020into\u0020the\u0020database.",
            "url": "classes/App-DataFixtures-LessonFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003AgetDependencies\u0028\u0029",
            "name": "getDependencies",
            "summary": "Returns\u0020an\u0020array\u0020of\u0020fixture\u0020dependencies.",
            "url": "classes/App-DataFixtures-LessonFixtures.html#method_getDependencies"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003ALESSON_GUITARE_n\u00B01_REFERENCE",
            "name": "LESSON_GUITARE_n\u00B01_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-LessonFixtures.html#constant_LESSON_GUITARE_n%C2%B01_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003ALESSON_GUITARE_n\u00B02_REFERENCE",
            "name": "LESSON_GUITARE_n\u00B02_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-LessonFixtures.html#constant_LESSON_GUITARE_n%C2%B02_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003ALESSON_PIANO_n\u00B01_REFERENCE",
            "name": "LESSON_PIANO_n\u00B01_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-LessonFixtures.html#constant_LESSON_PIANO_n%C2%B01_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003ALESSON_PIANO_n\u00B02_REFERENCE",
            "name": "LESSON_PIANO_n\u00B02_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-LessonFixtures.html#constant_LESSON_PIANO_n%C2%B02_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003ALESSON_DEVELOPPEMENT_n\u00B01_REFERENCE",
            "name": "LESSON_DEVELOPPEMENT_n\u00B01_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-LessonFixtures.html#constant_LESSON_DEVELOPPEMENT_n%C2%B01_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003ALESSON_DEVELOPPEMENT_n\u00B02_REFERENCE",
            "name": "LESSON_DEVELOPPEMENT_n\u00B02_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-LessonFixtures.html#constant_LESSON_DEVELOPPEMENT_n%C2%B02_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003ALESSON_JARDINAGE_n\u00B01_REFERENCE",
            "name": "LESSON_JARDINAGE_n\u00B01_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-LessonFixtures.html#constant_LESSON_JARDINAGE_n%C2%B01_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003ALESSON_JARDINAGE_n\u00B02_REFERENCE",
            "name": "LESSON_JARDINAGE_n\u00B02_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-LessonFixtures.html#constant_LESSON_JARDINAGE_n%C2%B02_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003ALESSON_CUISINE_n\u00B01_REFERENCE",
            "name": "LESSON_CUISINE_n\u00B01_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-LessonFixtures.html#constant_LESSON_CUISINE_n%C2%B01_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003ALESSON_CUISINE_n\u00B02_REFERENCE",
            "name": "LESSON_CUISINE_n\u00B02_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-LessonFixtures.html#constant_LESSON_CUISINE_n%C2%B02_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003ALESSON_DRESSAGE_n\u00B01_REFERENCE",
            "name": "LESSON_DRESSAGE_n\u00B01_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-LessonFixtures.html#constant_LESSON_DRESSAGE_n%C2%B01_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\LessonFixtures\u003A\u003ALESSON_DRESSAGE_n\u00B02_REFERENCE",
            "name": "LESSON_DRESSAGE_n\u00B02_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-LessonFixtures.html#constant_LESSON_DRESSAGE_n%C2%B02_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\ThemeFixtures",
            "name": "ThemeFixtures",
            "summary": "Fixture\u0020class\u0020responsible\u0020for\u0020loading\u0020sample\u0020Theme\u0020data\u0020into\u0020the\u0020database.",
            "url": "classes/App-DataFixtures-ThemeFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\ThemeFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loads\u0020a\u0020set\u0020of\u0020predefined\u0020Theme\u0020entities\u0020into\u0020the\u0020database.",
            "url": "classes/App-DataFixtures-ThemeFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\ThemeFixtures\u003A\u003ATHEME_MUSIQUE_REFERENCE",
            "name": "THEME_MUSIQUE_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-ThemeFixtures.html#constant_THEME_MUSIQUE_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\ThemeFixtures\u003A\u003ATHEME_INFORMATIQUE_REFERENCE",
            "name": "THEME_INFORMATIQUE_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-ThemeFixtures.html#constant_THEME_INFORMATIQUE_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\ThemeFixtures\u003A\u003ATHEME_JARDINAGE_REFERENCE",
            "name": "THEME_JARDINAGE_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-ThemeFixtures.html#constant_THEME_JARDINAGE_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\ThemeFixtures\u003A\u003ATHEME_CUISINE_REFERENCE",
            "name": "THEME_CUISINE_REFERENCE",
            "summary": "",
            "url": "classes/App-DataFixtures-ThemeFixtures.html#constant_THEME_CUISINE_REFERENCE"
        },                {
            "fqsen": "\\App\\DataFixtures\\UserFixtures",
            "name": "UserFixtures",
            "summary": "Fixture\u0020class\u0020for\u0020loading\u0020sample\u0020User\u0020entities\u0020into\u0020the\u0020database.",
            "url": "classes/App-DataFixtures-UserFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\UserFixtures\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020method\u0020for\u0020injecting\u0020the\u0020password\u0020hasher.",
            "url": "classes/App-DataFixtures-UserFixtures.html#method___construct"
        },                {
            "fqsen": "\\App\\DataFixtures\\UserFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loads\u0020a\u0020set\u0020of\u0020predefined\u0020User\u0020entities\u0020into\u0020the\u0020database.",
            "url": "classes/App-DataFixtures-UserFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\UserFixtures\u003A\u003A\u0024hasher",
            "name": "hasher",
            "summary": "",
            "url": "classes/App-DataFixtures-UserFixtures.html#property_hasher"
        },                {
            "fqsen": "\\App\\Security\\AccessDeniedHandler",
            "name": "AccessDeniedHandler",
            "summary": "Handles\u0020access\u0020denial\u0020in\u0020the\u0020application\u0020by\u0020redirecting\u0020unauthorized\u0020users\nto\u0020the\u0020login\u0020page\u0020or\u0020another\u0020appropriate\u0020route.",
            "url": "classes/App-Security-AccessDeniedHandler.html"
        },                {
            "fqsen": "\\App\\Security\\AccessDeniedHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020AccessDeniedHandler.",
            "url": "classes/App-Security-AccessDeniedHandler.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\AccessDeniedHandler\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handles\u0020AccessDeniedException\u0020by\u0020redirecting\u0020to\u0020a\u0020login\u0020page\u0020or\u0020custom\u0020route.",
            "url": "classes/App-Security-AccessDeniedHandler.html#method_handle"
        },                {
            "fqsen": "\\App\\Security\\AccessDeniedHandler\u003A\u003A\u0024router",
            "name": "router",
            "summary": "",
            "url": "classes/App-Security-AccessDeniedHandler.html#property_router"
        },                {
            "fqsen": "\\App\\Security\\CourseVoter",
            "name": "CourseVoter",
            "summary": "CourseVoter\u0020is\u0020responsible\u0020for\u0020checking\u0020if\u0020a\u0020user\u0020can\u0020access\u0020a\u0020specific\u0020course.",
            "url": "classes/App-Security-CourseVoter.html"
        },                {
            "fqsen": "\\App\\Security\\CourseVoter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Security-CourseVoter.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\CourseVoter\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "Determines\u0020if\u0020the\u0020voter\u0020supports\u0020the\u0020given\u0020attribute\u0020and\u0020subject.",
            "url": "classes/App-Security-CourseVoter.html#method_supports"
        },                {
            "fqsen": "\\App\\Security\\CourseVoter\u003A\u003AvoteOnAttribute\u0028\u0029",
            "name": "voteOnAttribute",
            "summary": "Perform\u0020the\u0020authorization\u0020logic\u0020for\u0020the\u0020supported\u0020attribute\u0020and\u0020subject.",
            "url": "classes/App-Security-CourseVoter.html#method_voteOnAttribute"
        },                {
            "fqsen": "\\App\\Security\\CourseVoter\u003A\u003A\u0024entityManager",
            "name": "entityManager",
            "summary": "",
            "url": "classes/App-Security-CourseVoter.html#property_entityManager"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier",
            "name": "EmailVerifier",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier\u003A\u003AsendEmailConfirmation\u0028\u0029",
            "name": "sendEmailConfirmation",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html#method_sendEmailConfirmation"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier\u003A\u003AhandleEmailConfirmation\u0028\u0029",
            "name": "handleEmailConfirmation",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html#method_handleEmailConfirmation"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier\u003A\u003A\u0024verifyEmailHelper",
            "name": "verifyEmailHelper",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html#property_verifyEmailHelper"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier\u003A\u003A\u0024mailer",
            "name": "mailer",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html#property_mailer"
        },                {
            "fqsen": "\\App\\Security\\EmailVerifier\u003A\u003A\u0024entityManager",
            "name": "entityManager",
            "summary": "",
            "url": "classes/App-Security-EmailVerifier.html#property_entityManager"
        },                {
            "fqsen": "\\App\\Security\\UserAuthAuthenticator",
            "name": "UserAuthAuthenticator",
            "summary": "UserAuthAuthenticator\u0020is\u0020responsible\u0020for\u0020authenticating\u0020users\u0020during\u0020the\u0020login\u0020process.",
            "url": "classes/App-Security-UserAuthAuthenticator.html"
        },                {
            "fqsen": "\\App\\Security\\UserAuthAuthenticator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020for\u0020injecting\u0020the\u0020UrlGeneratorInterface.",
            "url": "classes/App-Security-UserAuthAuthenticator.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\UserAuthAuthenticator\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "This\u0020method\u0020is\u0020responsible\u0020for\u0020creating\u0020and\u0020returning\u0020a\u0020Passport\u0020object\u0020which\u0020holds\u0020user\u0020credentials.",
            "url": "classes/App-Security-UserAuthAuthenticator.html#method_authenticate"
        },                {
            "fqsen": "\\App\\Security\\UserAuthAuthenticator\u003A\u003AonAuthenticationSuccess\u0028\u0029",
            "name": "onAuthenticationSuccess",
            "summary": "Handles\u0020actions\u0020on\u0020successful\u0020authentication.\u0020If\u0020a\u0020target\u0020path\u0020is\u0020available\u0020\u0028stored\u0020previously\u0029,\u0020the\u0020user\u0020is\nredirected\u0020to\u0020that\u0020path,\u0020otherwise,\u0020they\u0020are\u0020redirected\u0020to\u0020the\u0020homepage.",
            "url": "classes/App-Security-UserAuthAuthenticator.html#method_onAuthenticationSuccess"
        },                {
            "fqsen": "\\App\\Security\\UserAuthAuthenticator\u003A\u003AgetLoginUrl\u0028\u0029",
            "name": "getLoginUrl",
            "summary": "",
            "url": "classes/App-Security-UserAuthAuthenticator.html#method_getLoginUrl"
        },                {
            "fqsen": "\\App\\Security\\UserAuthAuthenticator\u003A\u003ALOGIN_ROUTE",
            "name": "LOGIN_ROUTE",
            "summary": "",
            "url": "classes/App-Security-UserAuthAuthenticator.html#constant_LOGIN_ROUTE"
        },                {
            "fqsen": "\\App\\Security\\UserAuthAuthenticator\u003A\u003A\u0024urlGenerator",
            "name": "urlGenerator",
            "summary": "",
            "url": "classes/App-Security-UserAuthAuthenticator.html#property_urlGenerator"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\DataFixtures",
            "name": "DataFixtures",
            "summary": "",
            "url": "namespaces/app-datafixtures.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Security",
            "name": "Security",
            "summary": "",
            "url": "namespaces/app-security.html"
        }            ]
);
